/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInerface.WorkAreas.StudentRole;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ashleshadonde
 */
public class StudentSignUpJPanel extends javax.swing.JPanel {

    private final JPanel CardSequencePanel;
    private final Business business;
    
    
    /**
     * Creates new form StudentSignUpJPanel
     */
    public StudentSignUpJPanel(JPanel csp, Business b) {
        this.CardSequencePanel = csp;
        this.business = b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentSignUp = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();
        btnBackToLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        lblStudentSignUp.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblStudentSignUp.setText("Student Sign Up");

        lblFullName.setText("Full Name:");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtFullName.setColumns(15);
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        txtUsername.setColumns(15);

        txtPassword.setColumns(15);

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFullName)
                        .addGap(41, 41, 41)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addGap(40, 40, 40)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addGap(41, 41, 41)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateAccount)
                        .addGap(53, 53, 53)
                        .addComponent(btnBackToLogin))
                    .addComponent(lblStudentSignUp))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblStudentSignUp)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblFullName))
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblUsername))
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPassword))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAccount)
                    .addComponent(btnBackToLogin)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        String fullName = txtFullName.getText().trim();
    String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim(); // if you switch to JPasswordField: new String(txtPassword.getPassword())

    // Basic validation
    if (fullName.isEmpty() || username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return;
    }

    // Check for duplicate username
    UserAccountDirectory uad = business.getUserAccountDirectory();
    boolean exists = uad.getUserAccountList()
                        .stream()
                        .anyMatch(ua -> ua.getUserLoginName().equalsIgnoreCase(username));
    if (exists) {
        JOptionPane.showMessageDialog(this, "Username already taken. Please choose a different one.");
        return;
    }

    // Create Person -> StudentProfile -> UserAccount
    Person p = business.getPersonDirectory().newPerson(fullName);
    StudentProfile sp = business.getStudentDirectory().newStudentProfile(p);
    UserAccount ua = uad.newUserAccount(sp, username, password); // signature: (Profile, username, password)

    if (ua == null) {
        JOptionPane.showMessageDialog(this, "Could not create account. Please try again.");
        return;
    }

    JOptionPane.showMessageDialog(this, "Account created! You can now log in as Student.");

    // Clear fields
    txtFullName.setText("");
    txtUsername.setText("");
    txtPassword.setText("");

    // Go back to Login screen
    CardLayout cl = (CardLayout) CardSequencePanel.getLayout();
    cl.previous(CardSequencePanel);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) CardSequencePanel.getLayout();
        cl.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackToLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStudentSignUp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
